version: '3.7'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass

  postgres:
    image: postgres:14
    container_name: postgresql-container
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass

  gate-simulator:
    image: node:18-alpine
    container_name: gate-simulator
    working_dir: /app
    volumes:
      - ./gate-simulator:/app
    command: npm start
    ports:
      - "9999:9999"
    depends_on:
      - mysql
      - postgres

volumes:
  mysql_data:
  postgres_data: